"""The conformance suite.

"Same spec, both engines" is only a real claim if something checks it. These
tests assert on *observable behaviour* — which agents, skills, and tools each
engine actually materialised, and where the workflow starts — rather than on
generated bytes. Snapshot tests over emitted files are useful too (see
`test_langgraph_emitter.py`), but they check that output did not change, which
is a different and weaker guarantee.

Every backend in the registry is covered automatically, so a third engine
inherits this suite by existing.
"""

from __future__ import annotations

import ast
from pathlib import Path

import pytest

from agentbridge.backends import registry
from agentbridge.diagnostics import DiagnosticBag
from agentbridge.ir.models import Bundle, EngineContract, WorkflowMode
from agentbridge.spec import parse_spec

ENGINES = registry.names()


def _emit(bundle: Bundle, engine: str) -> tuple[list, EngineContract, DiagnosticBag]:
    backend = registry.get(engine)
    bag = DiagnosticBag()
    files = backend.emit(bundle, bag)
    return files, backend.contract(bundle, files), bag


@pytest.fixture
def bundle(example_spec: Path) -> Bundle:
    parsed, bag = parse_spec(example_spec)
    assert not bag.has_errors, [d.format() for d in bag]
    return parsed


@pytest.mark.parametrize("engine", ENGINES)
def test_every_backend_emits_without_errors(bundle: Bundle, engine: str) -> None:
    _, _, bag = _emit(bundle, engine)
    assert not bag.has_errors, [d.format() for d in bag]


@pytest.mark.parametrize("engine", ENGINES)
def test_every_agent_is_materialised(bundle: Bundle, engine: str) -> None:
    _, contract, _ = _emit(bundle, engine)
    assert contract.agents == frozenset(bundle.agents), f"{engine} did not materialise every agent"


@pytest.mark.parametrize("engine", ENGINES)
def test_every_skill_is_materialised(bundle: Bundle, engine: str) -> None:
    _, contract, _ = _emit(bundle, engine)
    assert contract.skills == frozenset(bundle.skills)


@pytest.mark.parametrize("engine", ENGINES)
def test_every_tool_is_materialised(bundle: Bundle, engine: str) -> None:
    _, contract, _ = _emit(bundle, engine)
    assert contract.tools == frozenset(bundle.tools)


@pytest.mark.parametrize("engine", ENGINES)
def test_declared_nodes_survive(bundle: Bundle, engine: str) -> None:
    _, contract, _ = _emit(bundle, engine)
    assert contract.nodes == {n.name for n in bundle.workflow.nodes}
    assert contract.entry == bundle.workflow.entry


def test_all_backends_agree(bundle: Bundle) -> None:
    """The load-bearing assertion: no engine quietly drops anything."""
    contracts = [_emit(bundle, engine)[1] for engine in ENGINES]
    reference = contracts[0]
    for other in contracts[1:]:
        differences = other.differences(reference)
        assert not differences, "\n".join(differences)


@pytest.mark.parametrize("engine", ENGINES)
def test_every_lossy_row_actually_reports(bundle: Bundle, minimal_spec: Path, engine: str) -> None:
    """Each lossy row in the mapping table must fire when its case is exercised.

    Two specs are needed to cover them all: the graph example exercises
    declared control flow, a Python-callable tool, typed state and a branch
    condition; the autonomous spec exercises the missing-structure case. A
    lossy row that never produces a diagnostic is a silent drop, which is the
    one thing the design forbids.
    """
    from agentbridge.mapping import lossy_rows

    expected = {row.diagnostic for row in lossy_rows(engine) if row.diagnostic}
    if not expected:
        pytest.skip(f"{engine} has no lossy rows")

    autonomous, _ = parse_spec(minimal_spec)
    reported = _emit(bundle, engine)[2].codes() | _emit(autonomous, engine)[2].codes()
    missing = expected - reported
    assert not missing, (
        f"{engine} declares lossy rows {sorted(missing)} that never emit a diagnostic"
    )


@pytest.mark.parametrize("engine", ENGINES)
def test_autonomous_spec_compiles_on_every_engine(minimal_spec: Path, engine: str) -> None:
    """A spec with no declared structure must still produce something runnable."""
    parsed, _ = parse_spec(minimal_spec)
    assert parsed.workflow.mode is WorkflowMode.AUTONOMOUS
    files, contract, bag = _emit(parsed, engine)
    assert files
    assert not bag.has_errors
    assert contract.agents == frozenset({"helper"})


def test_autonomous_spec_warns_where_it_is_lossy(minimal_spec: Path) -> None:
    """Flattening a multi-agent autonomous spec must not happen silently."""
    parsed, _ = parse_spec(minimal_spec)
    _, _, bag = _emit(parsed, "langgraph")
    assert "BRIDGE200" in bag.codes()


@pytest.mark.parametrize("engine", ENGINES)
def test_emitted_python_is_syntactically_valid(bundle: Bundle, engine: str) -> None:
    files, _, _ = _emit(bundle, engine)
    python_files = [f for f in files if str(f.path).endswith(".py")]
    for f in python_files:
        try:
            ast.parse(f.content, filename=str(f.path))
        except SyntaxError as exc:  # pragma: no cover - failure path
            pytest.fail(f"{engine} emitted invalid Python in {f.path}: {exc}")


@pytest.mark.parametrize("engine", ENGINES)
def test_emitted_paths_are_relative_and_contained(bundle: Bundle, engine: str) -> None:
    files, _, _ = _emit(bundle, engine)
    for f in files:
        assert not f.path.is_absolute()
        assert ".." not in f.path.parts
