"""IR -> a runnable LangGraph program.

Emits a small Python package rather than one file, so each concern lands
somewhere a human can read and edit: state shape, tool wiring, skill lowering,
agent construction, graph assembly.

Two decisions worth knowing before editing this module:

* Skills become tools whose return value is the skill body. This is the
  canonical lowering; the reasoning (and the rejected alternatives) live in
  `agentbridge.mapping.concepts`.
* `build_graph()` takes an injectable `model_factory`. That is not a testing
  afterthought — it is what lets the conformance suite build the real graph
  without an API key, and it is also the seam a deployment target uses to swap
  in a different provider.
"""

from __future__ import annotations

from agentbridge.backends.base import EmittedFile, RuntimeBackend
from agentbridge.diagnostics import DiagnosticBag
from agentbridge.ir.models import (
    END,
    Agent,
    Bundle,
    EngineContract,
    FieldType,
    Reducer,
    Skill,
    WorkflowMode,
)

PACKAGE = "workflow"
GENERATED_HEADER = '"""Generated by agentbridge. Edit the spec, not this file."""'


class LangGraphBackend(RuntimeBackend):
    name = "langgraph"
    description = "A runnable LangGraph program (StateGraph, nodes, conditional edges)."

    def emit(self, bundle: Bundle, diagnostics: DiagnosticBag) -> list[EmittedFile]:
        if bundle.workflow.mode is WorkflowMode.AUTONOMOUS:
            self._warn_autonomous(bundle, diagnostics)

        files = [
            EmittedFile(path=f"{PACKAGE}/__init__.py", content=_init_py(bundle)),
            EmittedFile(path=f"{PACKAGE}/state.py", content=_state_py(bundle)),
            EmittedFile(path=f"{PACKAGE}/skills.py", content=_skills_py(bundle, diagnostics)),
            EmittedFile(path=f"{PACKAGE}/tools.py", content=_tools_py(bundle, diagnostics)),
            EmittedFile(path=f"{PACKAGE}/agents.py", content=_agents_py(bundle)),
            EmittedFile(path=f"{PACKAGE}/graph.py", content=_graph_py(bundle)),
            EmittedFile(path="requirements.txt", content=_requirements()),
            EmittedFile(path="README.md", content=_readme(bundle)),
        ]
        return files

    def contract(self, bundle: Bundle, files: list[EmittedFile]) -> EngineContract:
        by_path = {str(f.path): f.content for f in files}
        agents_src = by_path.get(f"{PACKAGE}/agents.py", "")
        tools_src = by_path.get(f"{PACKAGE}/tools.py", "")
        skills_src = by_path.get(f"{PACKAGE}/skills.py", "")
        graph_src = by_path.get(f"{PACKAGE}/graph.py", "")

        agents = {a.name for a in bundle.ordered_agents() if _node_fn(a.name) in agents_src}
        tools = {t.name for t in bundle.ordered_tools() if _tool_var(t.name) in tools_src}
        skills = {s.name for s in bundle.ordered_skills() if _skill_var(s.name) in skills_src}
        nodes = {n.name for n in bundle.workflow.nodes if f'"{n.name}"' in graph_src}
        entry = bundle.workflow.entry
        if bundle.workflow.mode is WorkflowMode.AUTONOMOUS:
            # The flattened single node stands in for the whole workflow, and
            # the contract must say so rather than claim the declared nodes.
            nodes = {_autonomous_node(bundle)} if bundle.agents else set()
            entry = next(iter(sorted(nodes)), None)
        return EngineContract(
            engine=self.name,
            agents=frozenset(agents),
            skills=frozenset(skills),
            tools=frozenset(tools),
            nodes=frozenset(nodes),
            entry=entry,
        )

    def _warn_autonomous(self, bundle: Bundle, diagnostics: DiagnosticBag) -> None:
        extra = sorted(set(bundle.agents) - {_autonomous_node(bundle)}) if bundle.agents else []
        diagnostics.warn(
            "BRIDGE200",
            f"workflow {bundle.workflow.name!r} declares no graph, so it compiles "
            f"to a single node running {_autonomous_node(bundle)!r}"
            + (f"; {len(extra)} other agent(s) are unreachable: {extra}" if extra else ""),
            location=bundle.workflow.location,
            hint="add a graph: section to workflow.yaml to keep multi-agent structure",
        )


# --------------------------------------------------------------------------
# naming
# --------------------------------------------------------------------------


def _ident(name: str) -> str:
    out = "".join(c if c.isalnum() else "_" for c in name)
    return f"_{out}" if out and out[0].isdigit() else out


def _node_fn(agent_name: str) -> str:
    return f"make_{_ident(agent_name)}_node"


def _tool_var(tool_name: str) -> str:
    return f"tool_{_ident(tool_name)}"


def _skill_var(skill_name: str) -> str:
    return f"skill_{_ident(skill_name)}"


def _autonomous_node(bundle: Bundle) -> str:
    """The single agent an autonomous workflow collapses onto."""
    return sorted(bundle.agents)[0] if bundle.agents else "agent"


def _literal(value: str) -> str:
    """A readable Python string literal — generated code gets read."""
    if '"""' not in value and "\\" not in value and not value.endswith('"'):
        return f'"""{value}"""'
    return repr(value)


# --------------------------------------------------------------------------
# state.py
# --------------------------------------------------------------------------


def _state_py(bundle: Bundle) -> str:
    schema = bundle.workflow.state
    lines = [
        GENERATED_HEADER,
        "",
        "from __future__ import annotations",
        "",
        "import operator",
        "from typing import Annotated, Any, TypedDict",
        "",
    ]

    has_messages = schema.transcript_field is not None
    has_merge = any(f.reducer is Reducer.MERGE for f in schema.fields)
    if has_messages:
        lines += [
            "from langchain_core.messages import AnyMessage",
            "from langgraph.graph.message import add_messages",
            "",
        ]
    if has_merge:
        lines += [
            "",
            "def merge_dicts(left: dict[str, Any], right: dict[str, Any]) -> dict[str, Any]:",
            '    """Reducer for `merge` fields: right-hand keys win."""',
            "    return {**left, **right}",
            "",
        ]

    lines += ["", f"class {schema.name}(TypedDict, total=False):"]
    if not schema.fields:
        lines.append('    """No state fields were declared in the spec."""')
        lines.append("")
        return "\n".join(lines) + "\n"

    doc = ['    """State carried between nodes.', ""]
    for field in schema.fields:
        doc.append(f"    {field.name}: {field.description or field.type.value}")
    doc += ['    """', ""]
    lines += doc

    for field in schema.fields:
        lines.append(f"    {field.name}: {_annotation(field)}")
    lines.append("")
    return "\n".join(lines) + "\n"


_BASE_TYPES = {
    FieldType.STR: "str",
    FieldType.INT: "int",
    FieldType.FLOAT: "float",
    FieldType.BOOL: "bool",
    FieldType.LIST: "list[Any]",
    FieldType.DICT: "dict[str, Any]",
    FieldType.MESSAGES: "list[AnyMessage]",
}


def _annotation(field: object) -> str:
    ftype: FieldType = field.type  # type: ignore[attr-defined]
    reducer: Reducer = field.reducer  # type: ignore[attr-defined]
    base = _BASE_TYPES[ftype]
    if ftype is FieldType.MESSAGES:
        return f"Annotated[{base}, add_messages]"
    if reducer is Reducer.APPEND:
        return f"Annotated[{base}, operator.add]"
    if reducer is Reducer.MERGE:
        return f"Annotated[{base}, merge_dicts]"
    return base


# --------------------------------------------------------------------------
# skills.py — the canonical skill lowering
# --------------------------------------------------------------------------


def _skills_py(bundle: Bundle, diagnostics: DiagnosticBag) -> str:
    lines = [
        '"""Skills, lowered to tools. Generated by agentbridge.',
        "",
        "LangGraph has no lazy, model-triggered instruction primitive. Each skill",
        "becomes a zero-argument tool whose return value is the skill body, so the",
        "model still decides when to pull the instructions into context and pays",
        "no token cost until it does. The skill description becomes the tool",
        "description, which is what the model routes on.",
        '"""',
        "",
        "from __future__ import annotations",
        "",
        "from langchain_core.tools import StructuredTool",
        "",
    ]

    if not bundle.skills:
        lines += ["", "SKILL_TOOLS: dict[str, StructuredTool] = {}", ""]
        return "\n".join(lines) + "\n"

    for skill in bundle.ordered_skills():
        diagnostics.info(
            "BRIDGE202",
            f"skill {skill.name!r} is lowered to a tool that returns its body",
            location=skill.location,
        )
        const = f"{_ident(skill.name).upper()}_BODY"
        fn = f"_load_{_ident(skill.name)}"
        lines += [
            "",
            f"{const} = {_literal(_skill_body(skill))}",
            "",
            "",
            f"def {fn}() -> str:",
            f"    {_literal(_skill_tool_description(skill))}",
            f"    return {const}",
            "",
            "",
            f"{_skill_var(skill.name)} = StructuredTool.from_function(",
            f"    func={fn},",
            f'    name="skill_{_ident(skill.name)}",',
            f"    description={_literal(_skill_tool_description(skill))},",
            ")",
        ]

    lines += [
        "",
        "",
        "SKILL_TOOLS: dict[str, StructuredTool] = {",
    ]
    for skill in bundle.ordered_skills():
        lines.append(f'    "{skill.name}": {_skill_var(skill.name)},')
    lines += ["}", ""]
    return "\n".join(lines) + "\n"


def _skill_body(skill: Skill) -> str:
    body = skill.body.strip() or f"(The {skill.name} skill has no body.)"
    if skill.resources:
        listed = "\n".join(f"- {r}" for r in skill.resources)
        body += f"\n\n## Bundled resources\n\n{listed}"
    return body


def _skill_tool_description(skill: Skill) -> str:
    return (
        f"{skill.description.strip()} "
        "Call this to load the full instructions before you act on them."
    )


# --------------------------------------------------------------------------
# tools.py
# --------------------------------------------------------------------------


def _tools_py(bundle: Bundle, diagnostics: DiagnosticBag) -> str:
    lines = [
        GENERATED_HEADER,
        "",
        "from __future__ import annotations",
        "",
        "from langchain_core.tools import StructuredTool",
        "",
    ]

    imports: list[str] = []
    bodies: list[str] = []

    for tool in bundle.ordered_tools():
        alias = f"_impl_{_ident(tool.name)}"
        if tool.implementation:
            module, _, attr = tool.implementation.partition(":")
            imports.append(f"from {module} import {attr} as {alias}")
        else:
            builtin = tool.builtin or ""
            shim = _BUILTIN_SHIMS.get(builtin)
            if shim is None:
                diagnostics.warn(
                    "BRIDGE201",
                    f"builtin tool {builtin!r} has no LangGraph equivalent; a stub "
                    "that raises NotImplementedError is emitted in its place",
                    location=tool.location,
                    hint=(
                        "supply an 'implementation:' for it, or use one of: "
                        f"{sorted(_BUILTIN_SHIMS)}"
                    ),
                )
                bodies += [
                    "",
                    "",
                    f"def {alias}(*args: object, **kwargs: object) -> str:",
                    f'    """Stub for builtin {builtin!r}, which this engine does not provide."""',
                    "    raise NotImplementedError(",
                    f'        "tool {tool.name!r} maps to engine builtin {builtin!r}, which "',
                    '        "LangGraph does not provide; supply an implementation in the spec"',
                    "    )",
                ]
            else:
                diagnostics.info(
                    "BRIDGE201",
                    f"builtin tool {builtin!r} is served by the agentbridge runtime shim "
                    f"{shim!r}, which is deliberately simpler than the native tool",
                    location=tool.location,
                )
                imports.append(f"from agentbridge.runtime.builtins import {shim} as {alias}")

    lines += sorted(set(imports))
    lines += bodies
    lines += ["", ""]

    for tool in bundle.ordered_tools():
        alias = f"_impl_{_ident(tool.name)}"
        if tool.parameters:
            lines.append(f"# declared parameter schema: {tool.parameters}")
            lines.append("# (inferred here from the callable's signature, which is authoritative)")
        lines += [
            f"{_tool_var(tool.name)} = StructuredTool.from_function(",
            f"    func={alias},",
            f'    name="{tool.name}",',
            f"    description={_literal(tool.description.strip())},",
            ")",
            "",
        ]

    lines += ["", "TOOLS: dict[str, StructuredTool] = {"]
    for tool in bundle.ordered_tools():
        lines.append(f'    "{tool.name}": {_tool_var(tool.name)},')
    lines += ["}", ""]
    return "\n".join(lines) + "\n"


#: Engine builtins the bridge can serve itself, so a spec that uses them
#: actually runs on both engines rather than merely compiling.
_BUILTIN_SHIMS = {
    "Read": "read_file",
    "Write": "write_file",
    "Edit": "edit_file",
    "Bash": "run_bash",
    "Glob": "glob_files",
    "Grep": "grep_files",
}


# --------------------------------------------------------------------------
# agents.py
# --------------------------------------------------------------------------


def _agents_py(bundle: Bundle) -> str:
    lines = [
        GENERATED_HEADER,
        "",
        "from __future__ import annotations",
        "",
        "from collections.abc import Callable",
        "from typing import Any",
        "",
        "from langchain_core.language_models import BaseChatModel",
        "",
        f"from {PACKAGE}.skills import SKILL_TOOLS",
        f"from {PACKAGE}.state import {bundle.workflow.state.name}",
        f"from {PACKAGE}.tools import TOOLS",
        "",
        "",
        "def _build_agent(model: BaseChatModel, tools: list[Any], prompt: str) -> Any:",
        '    """Build a tool-calling agent across the two prebuilt-agent APIs.',
        "",
        "    LangGraph 1.0 moved this into langchain and renamed the prompt",
        "    keyword, so the import path alone is not enough to tell them apart.",
        '    """',
        "    try:",
        "        from langchain.agents import create_agent",
        "    except ImportError:  # langgraph < 1.0",
        "        from langgraph.prebuilt import create_react_agent",
        "",
        "        return create_react_agent(model, tools=tools, prompt=prompt)",
        "    return create_agent(model, tools=tools, system_prompt=prompt)",
        "",
        "",
        "ModelFactory = Callable[..., BaseChatModel]",
        "",
        "",
        "def default_model_factory(",
        "    name: str,",
        "    *,",
        "    max_tokens: int | None = None,",
        "    effort: str | None = None,",
        "    temperature: float | None = None,",
        ") -> BaseChatModel:",
        '    """Build the chat model for an agent.',
        "",
        "    Swap this out via build_graph(model_factory=...) to change provider,",
        "    to stub the model in tests, or to route different agents elsewhere.",
        '    """',
        "    from langchain_anthropic import ChatAnthropic",
        "",
        '    kwargs: dict[str, Any] = {"model": name}',
        "    if max_tokens is not None:",
        '        kwargs["max_tokens"] = max_tokens',
        "    if temperature is not None:",
        '        kwargs["temperature"] = temperature',
        "    if effort is not None:",
        "        # Reasoning depth rides in the request body, not as a client kwarg.",
        '        kwargs["model_kwargs"] = {"output_config": {"effort": effort}}',
        "    return ChatAnthropic(**kwargs)",
        "",
    ]

    for agent in bundle.ordered_agents():
        lines += _agent_node(bundle, agent)

    return "\n".join(lines) + "\n"


def _agent_node(bundle: Bundle, agent: Agent) -> list[str]:
    model = agent.model or bundle.workflow.model
    tool_refs = [f'TOOLS["{t.name}"]' for t in bundle.agent_tools(agent)]
    tool_refs += [f'SKILL_TOOLS["{s.name}"]' for s in bundle.agent_skills(agent)]
    tools_expr = "[" + ", ".join(tool_refs) + "]" if tool_refs else "[]"

    prompt_const = f"{_ident(agent.name).upper()}_PROMPT"
    state = bundle.workflow.state.name
    transcript = bundle.workflow.state.transcript_field
    field = transcript.name if transcript else "messages"

    model_args = [f'"{model.name}"']
    if model.max_tokens is not None:
        model_args.append(f"max_tokens={model.max_tokens}")
    if model.effort is not None:
        model_args.append(f'effort="{model.effort.value}"')
    if model.temperature is not None:
        model_args.append(f"temperature={model.temperature}")

    return [
        "",
        f"{prompt_const} = {_literal(agent.prompt.strip() or agent.description)}",
        "",
        "",
        f"def {_node_fn(agent.name)}(",
        "    model_factory: ModelFactory | None = None,",
        f") -> Callable[[{state}], dict[str, Any]]:",
        f'    """Build the node for the {agent.name!r} agent.',
        "",
        f"    {agent.description}",
        '    """',
        "    factory = model_factory or default_model_factory",
        f"    model = factory({', '.join(model_args)})",
        f"    agent = _build_agent(model, {tools_expr}, {prompt_const})",
        "",
        f"    def node(state: {state}) -> dict[str, Any]:",
        f'        history = list(state.get("{field}", []))',
        '        result = agent.invoke({"messages": history})',
        "        # Return only what this turn added; the reducer merges it in.",
        f'        return {{"{field}": result["messages"][len(history):]}}',
        "",
        f'    node.__name__ = "{_ident(agent.name)}"',
        "    return node",
        "",
    ]


# --------------------------------------------------------------------------
# graph.py
# --------------------------------------------------------------------------


def _graph_py(bundle: Bundle) -> str:
    wf = bundle.workflow
    state = wf.state.name
    lines = [
        GENERATED_HEADER,
        "",
        "from __future__ import annotations",
        "",
        "from typing import Any",
        "",
        "from langgraph.graph import END, StateGraph",
        "",
        f"from {PACKAGE} import agents as _agents",
        f"from {PACKAGE}.agents import ModelFactory",
        f"from {PACKAGE}.state import {state}",
        "",
    ]

    if wf.mode is WorkflowMode.GRAPH:
        for branch in wf.branches:
            module, _, attr = branch.condition.partition(":")
            lines.append(f"from {module} import {attr} as _route_{_ident(branch.source)}")
        if wf.branches:
            lines.append("")
        for node in wf.nodes:
            if node.function:
                module, _, attr = node.function.partition(":")
                lines.append(f"from {module} import {attr} as _fn_{_ident(node.name)}")
        lines.append("")

    lines += [
        "",
        "def build_graph(",
        "    config: Any = None,",
        "    *,",
        "    checkpointer: Any = None,",
        "    model_factory: ModelFactory | None = None,",
        ") -> Any:",
        f'    """Assemble the {wf.name!r} workflow.',
        "",
        f"    {wf.description}",
        "",
        "    `config` is accepted and ignored so this doubles as a LangGraph",
        "    Platform graph factory. Leave `checkpointer` unset when deployed —",
        "    the platform supplies its own.",
        '    """',
        f"    builder = StateGraph({state})",
    ]

    if wf.mode is WorkflowMode.GRAPH:
        lines += _graph_body(bundle)
    else:
        lines += _autonomous_body(bundle)

    lines += [
        "    return builder.compile(checkpointer=checkpointer)",
        "",
        "",
        '__all__ = ["build_graph"]',
    ]
    return "\n".join(lines) + "\n"


def _graph_body(bundle: Bundle) -> list[str]:
    wf = bundle.workflow
    out: list[str] = []
    for node in wf.nodes:
        if node.agent:
            factory = f"_agents.{_node_fn(node.agent)}(model_factory)"
        else:
            factory = f"_fn_{_ident(node.name)}"
        out.append(f'    builder.add_node("{node.name}", {factory})')

    out.append("")
    out.append(f'    builder.set_entry_point("{wf.entry}")')
    for edge in wf.edges:
        target = "END" if edge.target == END else f'"{edge.target}"'
        out.append(f'    builder.add_edge("{edge.source}", {target})')

    for branch in wf.branches:
        mapping = ", ".join(
            f'"{label}": ' + ("END" if target == END else f'"{target}"')
            for label, target in sorted(branch.targets.items())
        )
        out += [
            "",
            f"    # {branch.description}",
            "    builder.add_conditional_edges(",
            f'        "{branch.source}",',
            f"        _route_{_ident(branch.source)},",
            "        {" + mapping + "},",
            "    )",
        ]
    out.append("")
    return out


def _autonomous_body(bundle: Bundle) -> list[str]:
    """One node, because a spec with no declared structure has no graph.

    Documented in the generated file too — someone reading the output should
    not have to guess why their four agents became one node.
    """
    agent = _autonomous_node(bundle)
    return [
        "    # The spec declared no graph, so there is no structure to build.",
        "    # This is a single node running one agent's own tool-calling loop.",
        "    # Add a graph: section to workflow.yaml to keep multi-agent structure.",
        f'    builder.add_node("{agent}", _agents.{_node_fn(agent)}(model_factory))',
        f'    builder.set_entry_point("{agent}")',
        f'    builder.add_edge("{agent}", END)',
        "",
    ]


# --------------------------------------------------------------------------
# supporting files
# --------------------------------------------------------------------------


def _init_py(bundle: Bundle) -> str:
    return "\n".join(
        [
            f'"""{bundle.workflow.name}: generated by agentbridge."""',
            "",
            f"from {PACKAGE}.graph import build_graph",
            "",
            '__all__ = ["build_graph"]',
            "",
        ]
    )


def _requirements() -> str:
    return "\n".join(
        [
            "langgraph>=0.3.0",
            "langchain-core>=0.3.0",
            "langchain-anthropic>=0.3.0",
            "",
            "# LangGraph 1.0 moved the prebuilt agent to langchain.agents.create_agent.",
            "# workflow/agents.py works with or without this; installing it takes the",
            "# current path instead of the deprecated langgraph.prebuilt one.",
            "langchain>=1.0",
            "",
            "# The bridge's builtin tool shims (read/write/bash/glob/grep). Only",
            "# needed if the spec declares a tool with `builtin:`.",
            "agentbridge",
            "",
        ]
    )


def _readme(bundle: Bundle) -> str:
    wf = bundle.workflow
    autonomous = wf.mode is WorkflowMode.AUTONOMOUS
    lines = [
        f"# {wf.name} (LangGraph)",
        "",
        wf.description,
        "",
        "Generated by agentbridge. Edit the spec, not these files.",
        "",
        "## Run it",
        "",
        "```bash",
        "pip install -r requirements.txt",
        "export ANTHROPIC_API_KEY=...",
        'python -c "from workflow import build_graph; '
        "print(build_graph().invoke({'messages': [('user', 'hello')]}))\"",
        "```",
        "",
        "## Layout",
        "",
        "| File | What it holds |",
        "|---|---|",
        f"| `{PACKAGE}/state.py` | The typed state and its reducers |",
        f"| `{PACKAGE}/tools.py` | Tool wiring |",
        f"| `{PACKAGE}/skills.py` | Skills, lowered to load-on-demand tools |",
        f"| `{PACKAGE}/agents.py` | One node factory per agent |",
        f"| `{PACKAGE}/graph.py` | Graph assembly and `build_graph()` |",
        "",
        "## Swapping the model",
        "",
        "`build_graph(model_factory=...)` replaces `default_model_factory`. Use it",
        "to change provider, route agents to different models, or stub the model",
        "in tests.",
        "",
    ]
    if autonomous:
        lines += [
            "## Note on structure",
            "",
            "This spec declared no graph, so the program is a single node running",
            f"the `{_autonomous_node(bundle)}` agent. Add a `graph:` section to",
            "`workflow.yaml` to keep multi-agent structure on this engine.",
            "",
        ]
    return "\n".join(lines)
