"""LangGraph Platform: `langgraph.json`, env template, deploy commands."""

from __future__ import annotations

import json

from agentbridge.backends.base import EmittedFile
from agentbridge.backends.langgraph.emitter import PACKAGE
from agentbridge.deploy.base import DeployCommand, DeploymentTarget
from agentbridge.diagnostics import DiagnosticBag
from agentbridge.ir.models import Bundle


class LangGraphPlatformTarget(DeploymentTarget):
    name = "langgraph-platform"
    engine = "langgraph"
    description = "LangGraph Platform (langgraph dev / langgraph up)."

    def prepare(
        self, bundle: Bundle, emitted: list[EmittedFile], diagnostics: DiagnosticBag
    ) -> list[EmittedFile]:
        graph_path = f"{PACKAGE}/graph.py"
        if not any(str(f.path) == graph_path for f in emitted):
            diagnostics.error(
                "BRIDGE500",
                f"{self.name} expected {graph_path} in the emitted output but did not find it",
                hint="compile with --engine langgraph before deploying",
            )
            return []

        manifest = {
            "dependencies": ["."],
            # A factory rather than a module-level variable: constructing the
            # graph at import time would need credentials just to import.
            "graphs": {bundle.workflow.name: f"./{graph_path}:build_graph"},
            "env": ".env",
        }
        return [
            EmittedFile(path="langgraph.json", content=json.dumps(manifest, indent=2) + "\n"),
            EmittedFile(path=".env.example", content=_env_example()),
            EmittedFile(path="DEPLOY.md", content=_deploy_md(self, bundle)),
        ]

    def commands(self, bundle: Bundle) -> list[DeployCommand]:
        return [
            DeployCommand(
                label="Install the CLI",
                command="pip install -U 'langgraph-cli[inmem]'",
            ),
            DeployCommand(
                label="Run locally with a live reload server",
                command="langgraph dev",
                note="Serves the graph and opens LangGraph Studio against it.",
            ),
            DeployCommand(
                label="Run the production container locally",
                command="langgraph up",
                note="Needs Docker. Closer to what the platform runs.",
            ),
            DeployCommand(
                label="Build a deployable image",
                command=f"langgraph build -t {bundle.workflow.name}:latest",
            ),
        ]


def _env_example() -> str:
    return "\n".join(
        [
            "# Copy to .env and fill in.",
            "ANTHROPIC_API_KEY=",
            "",
            "# Optional: tracing.",
            "# LANGSMITH_API_KEY=",
            "# LANGSMITH_TRACING=true",
            "",
        ]
    )


def _deploy_md(target: LangGraphPlatformTarget, bundle: Bundle) -> str:
    lines = [
        f"# Deploying {bundle.workflow.name}",
        "",
        f"Target: **{target.name}** — {target.description}",
        "",
        "Generated by agentbridge.",
        "",
        "## Steps",
        "",
    ]
    for index, command in enumerate(target.commands(bundle), start=1):
        lines += [
            f"{index}. {command.label}",
            "",
            "   ```bash",
            f"   {command.command}",
            "   ```",
            "",
        ]
        if command.note:
            lines += [f"   {command.note}", ""]

    lines += [
        "## Notes",
        "",
        "- `langgraph.json` points at `build_graph` as a factory rather than a",
        "  module-level graph object, so importing the module does not require",
        "  credentials.",
        "- Do not pass a `checkpointer` when deployed; the platform supplies one.",
        "",
    ]
    return "\n".join(lines)
